from collections.abc import Iterator
from http import server
from pathlib import Path

import pytest
from pytest import MonkeyPatch

from appenv import UvBin

def _create_fake_uv_binary(directory: Path) -> Path: ...
def _create_fake_tarball(triple: str, fake_binary: Path) -> bytes: ...

class _FakeReleaseHandler(server.BaseHTTPRequestHandler):
    tarball_data: bytes
    def do_GET(self) -> None: ...
    def log_message(self, format: str, *args: object) -> None: ...

@pytest.fixture
def mock_github_server(tmp_path: Path) -> Iterator[tuple[str, str]]: ...
def _make_uv_bin(tmp_path: Path) -> UvBin: ...
def test_e2e_github_download_success(
    tmp_path: Path,
    monkeypatch: MonkeyPatch,
    mock_github_server: tuple[str, str],
) -> None: ...
def test_e2e_platform_triple() -> None: ...
def test_e2e_github_download_unsupported_platform(
    tmp_path: Path, monkeypatch: MonkeyPatch
) -> None: ...
def test_e2e_github_download_network_error(
    tmp_path: Path, monkeypatch: MonkeyPatch
) -> None: ...
def test_e2e_github_download_invalid_tarball(
    tmp_path: Path, monkeypatch: MonkeyPatch
) -> None: ...
def test_e2e_github_download_tarball_without_uv_entry(
    tmp_path: Path, monkeypatch: MonkeyPatch
) -> None: ...
