import sys
from pathlib import Path

import pytest

def _copy_appenv(tmp_path: Path) -> Path: ...
def _setup_project_with_lockfile(
    tmp_path: Path, *, app_name: str = "testapp"
) -> tuple[Path, Path]: ...
def test_e2e_version(tmp_path: Path) -> None: ...
def test_e2e_reset_no_venv(tmp_path: Path) -> None: ...
@pytest.mark.slow(reason="Needs prepare which requires uv to create venv")
def test_e2e_reset_after_prepare(tmp_path: Path) -> None: ...
def test_e2e_update_lockfile(tmp_path: Path) -> None: ...
def test_e2e_update_lockfile_verbose(tmp_path: Path) -> None: ...
def test_e2e_self_update_same_version(tmp_path: Path) -> None: ...
def test_e2e_self_update_no_script(tmp_path: Path) -> None: ...
@pytest.mark.parametrize(
    ("writes_pyproject", "expected_message"),
    [
        pytest.param(False, "No pyproject.toml found", id="no-pyproject"),
        pytest.param(True, "No uv.lock", id="no-lockfile"),
    ],
)
def test_e2e_prepare_no_pyproject_or_lockfile(
    tmp_path: Path, writes_pyproject: bool, expected_message: str
) -> None: ...
@pytest.mark.slow(reason="Needs prepare which requires uv to create venv")
@pytest.mark.parametrize(
    ("argv_tail", "expected_substring"),
    [
        pytest.param(
            ["python", "-c", "print('hello from e2e')"], "hello from e2e", id="python"
        ),
        pytest.param(
            ["run", "python", "-c", "print('run works')"], "run works", id="run"
        ),
    ],
)
def test_e2e_python_or_run_command(
    tmp_path: Path, argv_tail: list[str], expected_substring: str
) -> None: ...
def test_e2e_uv_command(tmp_path: Path) -> None: ...
@pytest.mark.slow(reason="Needs prepare which requires uv to create venv")
def test_e2e_prepare_creates_dot_venv_symlink(tmp_path: Path) -> None: ...
@pytest.mark.skipif(sys.platform == "win32", reason="pexpect not available on Windows")
def test_e2e_ensure_gitignore_created(tmp_path: Path) -> None: ...
def test_e2e_ensure_gitignore_updated(tmp_path: Path) -> None: ...
