from pathlib import Path

import pytest
from pytest import CaptureFixture, MonkeyPatch

@pytest.mark.no_mock_uv_version
def test_ensure_uv_returns_uvbin_from_path(
    monkeypatch: MonkeyPatch, tmp_path: Path
) -> None: ...
def test_pyproject_requires_python_edge_cases(tmp_path: Path) -> None: ...
def test_pyproject_requires_python_with_upper_bound(tmp_path: Path) -> None: ...
def test_pyproject_builder_merges_with_existing_content(tmp_path: Path) -> None: ...
def test_ensure_pyproject_no_project_section_no_requirements(
    tmp_path: Path, monkeypatch: MonkeyPatch, capsys: CaptureFixture[str]
) -> None: ...
def test_ensure_pyproject_no_file_with_requirements(
    tmp_path: Path, monkeypatch: MonkeyPatch, capsys: CaptureFixture[str]
) -> None: ...
def test_print_migration_info_skips_minimum_version_with_single_python(
    tmp_path: Path, capsys: CaptureFixture[str]
) -> None: ...
def test_pyproject_python_preference_empty_after_filter(
    tmp_path: Path, capsys: CaptureFixture[str]
) -> None: ...
