from pathlib import Path

from pytest import LogCaptureFixture

def test_grouped_help_formatter_skips_command_not_in_choices() -> None: ...
def test_grouped_help_formatter_truncates_long_help() -> None: ...
def test_colored_console_formatter_format() -> None: ...
def test_console_diagnostic_filter_hides_internal_diagnostics() -> None: ...
def test_setup_logging_verbose(tmp_path: Path, caplog: LogCaptureFixture) -> None: ...
