from pathlib import Path

def test_index_has_toctree(project_root: Path) -> None: ...
def test_index_toctree_lists_sections(project_root: Path) -> None: ...
def test_conf_suppress_warnings_only_myst(project_root: Path) -> None: ...
def test_pyi_declares_exit_code_usage(project_root: Path) -> None: ...
def test_index_uses_uv_run_not_bare_uv(project_root: Path) -> None: ...
def test_commands_doc_has_usage_exit_code(project_root: Path) -> None: ...
def test_dev_doc_has_usage_exit_code(project_root: Path) -> None: ...
def test_commands_doc_has_run_section(project_root: Path) -> None: ...
def test_index_mentions_supported_python_versions(project_root: Path) -> None: ...
def test_quickstart_uses_httpie(project_root: Path) -> None: ...
def test_init_prompt_matches_source(project_root: Path) -> None: ...
