# SPDX-FileCopyrightText: 2020 Flying Circus

import pytest
from pytest import CaptureFixture

def test_cmd_with_string_uses_shell() -> None: ...
def test_cmd_raises_value_error_on_failure() -> None: ...
def test_cmd_with_list_no_shell() -> None: ...
def test_cmd_forwards_explicit_env(monkeypatch: pytest.MonkeyPatch) -> None: ...
def test_cmd_default_env_is_not_none(monkeypatch: pytest.MonkeyPatch) -> None: ...
def test_cmd_error_output_not_quiet(capsys: CaptureFixture[str]) -> None: ...
