from collections.abc import Callable
from pathlib import Path

import pytest
from pytest import CaptureFixture, LogCaptureFixture

from tests.conftest import MockUvBin

def _write_old_lockfile(base: Path, content: str) -> None: ...
def _mock_uv_lock_writes(
    make_mock_uv: Callable[..., MockUvBin], new_lock_content: str
) -> MockUvBin: ...
def test_read_lockfile_lines_strips_and_filters(tmp_path: Path) -> None: ...
def test_read_lockfile_lines_missing_file(tmp_path: Path) -> None: ...
@pytest.mark.characterization
def test_read_lockfile_lines_inline_hash_kept(tmp_path: Path) -> None: ...
def test_read_lockfile_lines_empty_file(tmp_path: Path) -> None: ...
def test_read_lockfile_lines_returns_set(tmp_path: Path) -> None: ...
def test_diff_summary_updated(
    tmp_path: Path, file_content: str, input_set: set[str], expected: str
) -> None: ...
def test_diff_summary_created(tmp_path: Path) -> None: ...
def test_diff_summary_empty_to_empty_reports_no_changes(tmp_path: Path) -> None: ...
def test_diff_summary_counts_match_set_diff(tmp_path: Path) -> None: ...
def test_diff_returns_no_changes_when_identical(
    tmp_path: Path, make_mock_uv: Callable[..., MockUvBin], capsys: CaptureFixture[str]
) -> None: ...
def test_diff_returns_changed_when_modified(
    tmp_path: Path, make_mock_uv: Callable[..., MockUvBin], capsys: CaptureFixture[str]
) -> None: ...
def test_diff_copies_pyproject_to_tmpdir(
    tmp_path: Path, make_mock_uv: Callable[..., MockUvBin]
) -> None: ...
def test_diff_does_not_modify_original_lockfile(
    tmp_path: Path, make_mock_uv: Callable[..., MockUvBin]
) -> None: ...
def test_diff_when_uv_produces_no_lockfile_raises(
    tmp_path: Path,
    make_mock_uv: Callable[..., MockUvBin],
    caplog: LogCaptureFixture,
) -> None: ...
