#!/usr/bin/env bash
# ┌─────────────────────────────────────────────────────────────────────────┐
# │  appenv UX Test Environment Setup                                       │
# │                                                                         │
# │  Creates 16 scenarios across 4 tester personas for CLI UX evaluation.  │
# │                                                                         │
# │  Personas:                                                              │
# │    Anna   — Fresh user, first encounter with appenv                     │
# │    Bernd  — Dependency manager, version constraints & conflicts         │
# │    Claudia— Ops/production, broken states & recovery                    │
# │    Dieter — Migration from old appenv (requirements.txt + pip)          │
# │                                                                         │
# │  Usage:                                                                 │
# │    bash /appenv/scripts/setup-testenv.sh                                │
# │                                                                         │
# │  Test environments are created under:                                   │
# │    /appenv/tmp/appenv/<persona>/<scenario>/                             │
# │                                                                         │
# │  Each round starts fresh (rm -rf + rebuild).                            │
# └─────────────────────────────────────────────────────────────────────────┘
set -euo pipefail

# ── Environment ──────────────────────────────────────────────────────────
# Strip agent interceptors from PATH, ensure uv is available
export PATH="/srv/s-dev/.nix-profile/bin:$(
    echo "$PATH" \
        | tr ':' '\n' \
        | grep -v '/.agents/interceptors/' \
        | tr '\n' ':'
)"

BASE="/appenv/tmp/appenv"
APPENV_SRC="/appenv/src/appenv.py"

# ── Colors ───────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ── Helpers ──────────────────────────────────────────────────────────────

header() {
    echo ""
    echo -e "${BOLD}${BLUE}━━━ $1 ━━━${NC}"
    echo ""
}

info() {
    echo -e "  ${CYAN}▸${NC} $1"
}

ok() {
    echo -e "  ${GREEN}✓${NC} $1"
}

warn() {
    echo -e "  ${YELLOW}⚠${NC} $1"
}

fail() {
    echo -e "  ${RED}✗${NC} $1"
}

separator() {
    echo ""
    echo -e "  ${BLUE}─────────────────────────────────────────${NC}"
    echo ""
}

# ── Core Setup Functions ─────────────────────────────────────────────────

cleanup() {
    echo -e "${BOLD}${RED}🧹  Cleaning up ${BASE} ...${NC}"
    rm -rf "$BASE"
    mkdir -p "$BASE"
}

copy_appenv() {
    local dir="$1"
    cp "$APPENV_SRC" "$dir/appenv"
    chmod +x "$dir/appenv"
}

# Write a minimal pyproject.toml with optional dependencies
write_pyproject() {
    local dir="$1"
    local name="$2"
    shift 2

    cat > "$dir/pyproject.toml" <<HEADER
[project]
name = "${name}"
version = "0.1.0"
requires-python = ">=3.10"
HEADER

    if [[ $# -gt 0 ]]; then
        echo "dependencies = [" >> "$dir/pyproject.toml"
        for dep in "$@"; do
            echo "    \"${dep}\"," >> "$dir/pyproject.toml"
        done
        echo "]" >> "$dir/pyproject.toml"
    fi
    echo "" >> "$dir/pyproject.toml"
}

# Bootstrap a full venv: create lockfile then prepare
# Uses python3 directly since /usr/bin/env may not exist (NixOS)
bootstrap_venv() {
    local dir="$1"
    (cd "$dir" && python3 ./appenv update-lockfile 2>&1 && python3 ./appenv prepare 2>&1) || {
        fail "bootstrap_venv failed in $dir"
        return 1
    }
}

# Create a binary symlink pointing to appenv
make_symlink() {
    local dir="$1"
    local name="$2"
    ln -sf appenv "$dir/$name"
}

# Create old-style appenv directory structure (legacy hash-based venv)
create_old_appenv() {
    local dir="$1"
    local hash="${2:-abc123def456}"

    mkdir -p "$dir/.appenv/${hash}/bin"
    mkdir -p "$dir/.appenv/${hash}/lib"

    # Fake pyvenv.cfg
    cat > "$dir/.appenv/${hash}/pyvenv.cfg" <<CFG
home = /usr/bin
include-system-site-packages = false
version = 3.11.9
CFG

    # Fake python binary
    cat > "$dir/.appenv/${hash}/bin/python" <<'SCRIPT'
#!/bin/sh
echo "Python 3.11.9 (old appenv)"
SCRIPT
    chmod +x "$dir/.appenv/${hash}/bin/python"

    # .appenv/current symlink -> hash dir
    ln -sf "$hash" "$dir/.appenv/current"
}

# Write a requirements.txt
write_requirements() {
    local dir="$1"
    shift
    cat > "$dir/requirements.txt" <<REQ
# This file is autogenerated by pip-compile with Python 3.11
# To update, run: pip-compile requirements.in
REQ
    for dep in "$@"; do
        echo "$dep" >> "$dir/requirements.txt"
    done
}

# Write a requirements.lock (old appenv internal lockfile)
write_requirements_lock() {
    local dir="$1"
    shift
    cat > "$dir/requirements.lock" <<HEADER
# Lockfile generated by old appenv
# Format: package==version
HEADER
    for dep in "$@"; do
        echo "$dep" >> "$dir/requirements.lock"
    done
}


# ══════════════════════════════════════════════════════════════════════════
#  ANNA — Fresh User
# ══════════════════════════════════════════════════════════════════════════
#
#  Anna has never used appenv. She's bootstrapping a new project from
#  scratch. She needs to understand init, prepare, adding deps, and
#  running binaries via symlinks.
#
#  Scenarios:
#    01-fresh      — Empty directory, just appenv copied in
#    02-prepared   — Fully bootstrapped with httpie, http symlink
#    03-with-tests — src-layout with dev deps in dependency-groups
# ─────────────────────────────────────────────────────────────────────────

setup_anna() {
    header "ANNA — Fresh User (3 scenarios)"

    # ── 01-fresh ────────────────────────────────────────────
    local dir="$BASE/anna/01-fresh"
    info "01-fresh: Empty directory for interactive init"
    mkdir -p "$dir"
    copy_appenv "$dir"
    ok "Ready: empty dir + appenv binary"

    separator

    # ── 02-prepared ─────────────────────────────────────────
    dir="$BASE/anna/02-prepared"
    info "02-prepared: Bootstrapped with httpie + http symlink"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_pyproject "$dir" "anna-app" "httpie>=3.2"
    bootstrap_venv "$dir"
    make_symlink "$dir" "http"
    ok "Ready: pyproject.toml + venv + lock + http symlink"

    separator

    # ── 03-with-tests ───────────────────────────────────────
    dir="$BASE/anna/03-with-tests"
    info "03-with-tests: src-layout with dev deps"
    mkdir -p "$dir/src/myapp" "$dir/tests"
    copy_appenv "$dir"

    cat > "$dir/pyproject.toml" <<'TOML'
[project]
name = "myapp"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31",
]

[dependency-groups]
dev = [
    "pytest>=8.0",
    "ruff>=0.4",
]
TOML

    # src/myapp/__init__.py
    cat > "$dir/src/myapp/__init__.py" <<'PY'
"""My application package."""

__version__ = "0.1.0"
PY

    # src/myapp/core.py
    cat > "$dir/src/myapp/core.py" <<'PY'
"""Core application logic."""


def greet(name: str) -> str:
    """Return a greeting."""
    return f"Hello, {name}!"


def fetch_url(url: str) -> dict:
    """Fetch a URL and return status info. Requires requests."""
    import requests

    resp = requests.get(url, timeout=10)
    return {"status": resp.status_code, "url": url}
PY

    # tests/test_basic.py
    cat > "$dir/tests/test_basic.py" <<'PY'
"""Basic tests for myapp."""

from myapp.core import greet


def test_greet():
    assert greet("World") == "Hello, World!"


def test_greet_empty():
    assert greet("") == "Hello, !"
PY

    bootstrap_venv "$dir"
    ok "Ready: src-layout + tests + dev deps in dependency-groups"
}


# ══════════════════════════════════════════════════════════════════════════
#  BERND — Dependency Manager
# ══════════════════════════════════════════════════════════════════════════
#
#  Bernd manages dependency constraints. He tests version pinning,
#  conflict resolution, and constraint merging behavior.
#
#  Scenarios:
#    01-fresh       — Empty directory for constraint experiments
#    02-constrained — Has requests>=2.31,<3 and click>=8.0
#    03-hybrid      — Mixed exact pins (click==8.1.7) and ranges
# ─────────────────────────────────────────────────────────────────────────

setup_bernd() {
    header "BERND — Dependency Manager (3 scenarios)"

    # ── 01-fresh ────────────────────────────────────────────
    local dir="$BASE/bernd/01-fresh"
    info "01-fresh: Empty directory for constraint experiments"
    mkdir -p "$dir"
    copy_appenv "$dir"
    ok "Ready: empty dir + appenv binary"

    separator

    # ── 02-constrained ──────────────────────────────────────
    dir="$BASE/bernd/02-constrained"
    info "02-constrained: requests>=2.31,<3 + click>=8.0"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_pyproject "$dir" "constrained-app" \
        "requests>=2.31,<3" \
        "click>=8.0"
    bootstrap_venv "$dir"
    ok "Ready: constrained deps + venv + lock"

    separator

    # ── 03-hybrid ───────────────────────────────────────────
    dir="$BASE/bernd/03-hybrid"
    info "03-hybrid: click==8.1.7 (exact pin) + requests>=2.0,<3 (range) + urllib3>=1.26"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_pyproject "$dir" "hybrid-app" \
        "click==8.1.7" \
        "requests>=2.0,<3" \
        "urllib3>=1.26"
    bootstrap_venv "$dir"
    ok "Ready: mixed exact pins and ranges + venv + lock"
}


# ══════════════════════════════════════════════════════════════════════════
#  CLAUDIA — Ops / Production
# ══════════════════════════════════════════════════════════════════════════
#
#  Claudia runs appenv in production. She tests broken states,
#  recovery paths, and symlink routing edge cases.
#
#  Scenarios:
#    01-fresh                — Empty directory
#    02-production           — Full production setup with multiple symlinks
#    03-broken/missing-lock  — pyproject.toml + venv, but no uv.lock
#    03-broken/real-venv-dir — .venv is real directory (not symlink)
#    03-broken/invalid-toml  — Malformed pyproject.toml
#    03-broken/broken-symlink— .venv points to nonexistent target
#
#  Also creates "broken" symlink in each broken scenario for
#  testing non-appenv symlink routing (application_name != "appenv").
# ─────────────────────────────────────────────────────────────────────────

setup_claudia() {
    header "CLAUDIA — Ops/Production (7 scenarios)"

    # ── 01-fresh ────────────────────────────────────────────
    local dir="$BASE/claudia/01-fresh"
    info "01-fresh: Empty directory for production workflow"
    mkdir -p "$dir"
    copy_appenv "$dir"
    ok "Ready: empty dir + appenv binary"

    separator

    # ── 02-production ───────────────────────────────────────
    dir="$BASE/claudia/02-production"
    info "02-production: Full setup with httpie + http symlink"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_pyproject "$dir" "production-app" "httpie>=3.2"
    bootstrap_venv "$dir"
    make_symlink "$dir" "http"
    ok "Ready: production venv + lock + http symlink"

    separator

    # ── 03-broken/missing-lock ──────────────────────────────
    dir="$BASE/claudia/03-broken/missing-lock"
    info "03-broken/missing-lock: pyproject.toml + venv, but no uv.lock"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_pyproject "$dir" "missing-lock-app" "httpie>=3.2"
    bootstrap_venv "$dir"
    # Break: remove the lockfile
    rm -f "$dir/uv.lock"
    make_symlink "$dir" "broken"
    ok "Ready: missing uv.lock (broken symlink for routing test)"

    separator

    # ── 03-broken/real-venv-dir ─────────────────────────────
    dir="$BASE/claudia/03-broken/real-venv-dir"
    info "03-broken/real-venv-dir: .venv is real directory instead of symlink"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_pyproject "$dir" "real-venv-app" "httpie>=3.2"
    bootstrap_venv "$dir"
    # Break: replace .venv symlink with a real directory
    rm -f "$dir/.venv"
    mkdir -p "$dir/.venv/bin"
    echo "fake venv" > "$dir/.venv/pyvenv.cfg"
    make_symlink "$dir" "broken"
    ok "Ready: .venv is real dir, not symlink"

    separator

    # ── 03-broken/invalid-toml ──────────────────────────────
    dir="$BASE/claudia/03-broken/invalid-toml"
    info "03-broken/invalid-toml: Malformed pyproject.toml"
    mkdir -p "$dir"
    copy_appenv "$dir"
    # Write invalid TOML — missing closing bracket, unclosed string
    cat > "$dir/pyproject.toml" <<'BADTOML'
[project
name = "broken-app"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "httpie>=3.2",
BADTOML
    # Create stale .venv symlink pointing to where venv would be
    mkdir -p "$dir/.appenv"
    ln -sf "$dir/.appenv/venv" "$dir/.venv"
    make_symlink "$dir" "broken"
    ok "Ready: invalid TOML + stale .venv"

    separator

    # ── 03-broken/broken-symlink ────────────────────────────
    dir="$BASE/claudia/03-broken/broken-symlink"
    info "03-broken/broken-symlink: .venv points to nonexistent target"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_pyproject "$dir" "broken-symlink-app" "httpie>=3.2"
    bootstrap_venv "$dir"
    # Break: point .venv to a nonexistent path
    rm -f "$dir/.venv"
    ln -sf "/tmp/nonexistent-venv-dead-beef" "$dir/.venv"
    make_symlink "$dir" "broken"
    ok "Ready: .venv -> nonexistent path"
}


# ══════════════════════════════════════════════════════════════════════════
#  DIETER — Migration from Old Appenv
# ══════════════════════════════════════════════════════════════════════════
#
#  Dieter migrates from old appenv (requirements.txt + pip + hash-venvs)
#  to new appenv (pyproject.toml + uv). Each scenario represents a
#  different old-appenv state.
#
#  Scenarios:
#    01-old-basic      — Plain requirements.txt, no .appenv dir
#    02-old-with-hash  — requirements.txt + old hash-based .appenv/<hash>/
#    03-old-with-lock  — requirements.txt + requirements.lock + hash venv
#    04-new-comparison — Side-by-side old and new style for comparison
# ─────────────────────────────────────────────────────────────────────────

setup_dieter() {
    header "DIETER — Migration from Old Appenv (4 scenarios)"

    # ── 01-old-basic ────────────────────────────────────────
    local dir="$BASE/dieter/01-old-basic"
    info "01-old-basic: requirements.txt only, no .appenv dir"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_requirements "$dir" \
        "httpie>=3.2" \
        "requests>=2.31" \
        "click>=8.0"
    ok "Ready: bare requirements.txt, no venv"

    separator

    # ── 02-old-with-hash ────────────────────────────────────
    dir="$BASE/dieter/02-old-with-hash"
    info "02-old-with-hash: requirements.txt + old hash-based .appenv/"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_requirements "$dir" \
        "httpie>=3.2" \
        "requests>=2.31"
    create_old_appenv "$dir" "abc123def456"
    ok "Ready: requirements.txt + .appenv/abc123def456/ + .appenv/current"

    separator

    # ── 03-old-with-lock ────────────────────────────────────
    dir="$BASE/dieter/03-old-with-lock"
    info "03-old-with-lock: requirements.txt + requirements.lock + hash venv"
    mkdir -p "$dir"
    copy_appenv "$dir"
    write_requirements "$dir" \
        "httpie>=3.2" \
        "requests>=2.31"
    write_requirements_lock "$dir" \
        "httpie==3.2.4" \
        "requests==2.32.3" \
        "urllib3==2.2.2" \
        "certifi==2024.7.4" \
        "charset-normalizer==3.3.2" \
        "idna==3.7"
    create_old_appenv "$dir" "xyz789abc456"
    ok "Ready: requirements.txt + lock + .appenv/xyz789abc456/"

    separator

    # ── 04-new-comparison ───────────────────────────────────
    info "04-new-comparison: Side-by-side old vs new"

    # Old side
    local old_dir="$BASE/dieter/04-new-comparison/old"
    mkdir -p "$old_dir"
    copy_appenv "$old_dir"
    write_requirements "$old_dir" \
        "httpie>=3.2" \
        "requests>=2.31"
    create_old_appenv "$old_dir" "legacy123hash"
    ok "Old side: requirements.txt + hash venv"

    # New side
    local new_dir="$BASE/dieter/04-new-comparison/new"
    mkdir -p "$new_dir"
    copy_appenv "$new_dir"
    write_pyproject "$new_dir" "myapp" \
        "httpie>=3.2" \
        "requests>=2.31"
    bootstrap_venv "$new_dir"
    make_symlink "$new_dir" "http"
    ok "New side: pyproject.toml + venv + lock + http symlink"
}


# ══════════════════════════════════════════════════════════════════════════
#  VALIDATION — Quick smoke test
# ══════════════════════════════════════════════════════════════════════════

validate() {
    header "VALIDATION — Checking setup"

    local errors=0

    # Count expected directories
    local expected_dirs=(
        "anna/01-fresh"
        "anna/02-prepared"
        "anna/03-with-tests"
        "bernd/01-fresh"
        "bernd/02-constrained"
        "bernd/03-hybrid"
        "claudia/01-fresh"
        "claudia/02-production"
        "claudia/03-broken/missing-lock"
        "claudia/03-broken/real-venv-dir"
        "claudia/03-broken/invalid-toml"
        "claudia/03-broken/broken-symlink"
        "dieter/01-old-basic"
        "dieter/02-old-with-hash"
        "dieter/03-old-with-lock"
        "dieter/04-new-comparison/old"
        "dieter/04-new-comparison/new"
    )

    for d in "${expected_dirs[@]}"; do
        if [[ -d "$BASE/$d" ]]; then
            ok "$d"
        else
            fail "$d — MISSING"
            ((errors++))
        fi
    done

    echo ""
    info "Checking key files ..."

    # Anna 02: http symlink + venv
    [[ -L "$BASE/anna/02-prepared/http" ]] && ok "anna/02-prepared/http symlink" || { fail "anna/02-prepared/http symlink"; ((errors++)); }
    [[ -f "$BASE/anna/02-prepared/uv.lock" ]] && ok "anna/02-prepared/uv.lock" || { fail "anna/02-prepared/uv.lock"; ((errors++)); }

    # Anna 03: src layout + tests
    [[ -f "$BASE/anna/03-with-tests/src/myapp/__init__.py" ]] && ok "anna/03-with-tests src layout" || { fail "anna/03-with-tests src layout"; ((errors++)); }
    [[ -f "$BASE/anna/03-with-tests/tests/test_basic.py" ]] && ok "anna/03-with-tests tests" || { fail "anna/03-with-tests tests"; ((errors++)); }

    # Bernd 02: constrained deps
    [[ -f "$BASE/bernd/02-constrained/pyproject.toml" ]] && ok "bernd/02-constrained/pyproject.toml" || { fail "bernd/02-constrained/pyproject.toml"; ((errors++)); }

    # Bernd 03: hybrid deps
    [[ -f "$BASE/bernd/03-hybrid/pyproject.toml" ]] && ok "bernd/03-hybrid/pyproject.toml" || { fail "bernd/03-hybrid/pyproject.toml"; ((errors++)); }

    # Claudia 03: broken states
    [[ ! -f "$BASE/claudia/03-broken/missing-lock/uv.lock" ]] && ok "claudia/missing-lock: uv.lock correctly absent" || { fail "claudia/missing-lock: uv.lock should be absent"; ((errors++)); }
    [[ -d "$BASE/claudia/03-broken/real-venv-dir/.venv" && ! -L "$BASE/claudia/03-broken/real-venv-dir/.venv" ]] && ok "claudia/real-venv-dir: .venv is real dir" || { fail "claudia/real-venv-dir: .venv should be real dir"; ((errors++)); }
    [[ -L "$BASE/claudia/03-broken/broken-symlink/.venv" ]] && ok "claudia/broken-symlink: .venv is symlink" || { fail "claudia/broken-symlink: .venv should be symlink"; ((errors++)); }

    # Dieter: old-style structures
    [[ -f "$BASE/dieter/01-old-basic/requirements.txt" ]] && ok "dieter/01-old-basic/requirements.txt" || { fail "dieter/01-old-basic/requirements.txt"; ((errors++)); }
    [[ -L "$BASE/dieter/02-old-with-hash/.appenv/current" ]] && ok "dieter/02-old-with-hash/.appenv/current symlink" || { fail "dieter/02-old-with-hash/.appenv/current"; ((errors++)); }
    [[ -f "$BASE/dieter/03-old-with-lock/requirements.lock" ]] && ok "dieter/03-old-with-lock/requirements.lock" || { fail "dieter/03-old-with-lock/requirements.lock"; ((errors++)); }
    [[ -f "$BASE/dieter/04-new-comparison/new/uv.lock" ]] && ok "dieter/04-new-comparison/new/uv.lock" || { fail "dieter/04-new-comparison/new/uv.lock"; ((errors++)); }

    echo ""
    if [[ $errors -eq 0 ]]; then
        echo -e "${BOLD}${GREEN}  ✓ All ${#expected_dirs[@]} scenarios validated, 0 errors${NC}"
    else
        echo -e "${BOLD}${RED}  ✗ ${errors} error(s) found${NC}"
    fi
}


# ══════════════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════════════

main() {
    echo ""
    echo -e "${BOLD}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║  appenv UX Test Environment Setup                            ║${NC}"
    echo -e "${BOLD}║  4 personas, 16 scenarios                                    ║${NC}"
    echo -e "${BOLD}╚══════════════════════════════════════════════════════════════╝${NC}"

    cleanup

    setup_anna
    setup_bernd
    setup_claudia
    setup_dieter

    validate

    echo ""
    echo -e "${BOLD}━━━ Setup Complete ━━━${NC}"
    echo ""
    echo "  Test environments ready at: ${BASE}"
    echo ""
    echo "  Personas:"
    echo "    anna/    — 3 scenarios (fresh, prepared, with-tests)"
    echo "    bernd/   — 3 scenarios (fresh, constrained, hybrid)"
    echo "    claudia/ — 7 scenarios (fresh, production, 4x broken)"
    echo "    dieter/  — 4 scenarios (old-basic, old-hash, old-lock, comparison)"
    echo ""
    echo "  Quick start:"
    echo "    cd $BASE/anna/01-fresh"
    echo "    ./appenv init"
    echo ""
}

main "$@"
