import argparse
import logging
import re
from argparse import Namespace
from dataclasses import dataclass
from functools import cached_property
from pathlib import Path
from typing import Final, NamedTuple, NoReturn

__version__: Final[str]

log: logging.Logger

# Exit codes (BSD sysexits.h conventions)
EXIT_CODE_DATAERR: Final[int]
EXIT_CODE_NOINPUT: Final[int]
EXIT_CODE_UNAVAILABLE: Final[int]
EXIT_CODE_USAGE: Final[int]

# Format constants
MAX_HELP_TEXT_LENGTH: Final[int]
VERSION_PARTS_COUNT: Final[int]

class GroupedHelpFormatter(argparse.RawDescriptionHelpFormatter):
    def _format_action(self, action: argparse.Action) -> str: ...

class UsageArgumentParser(argparse.ArgumentParser):
    def error(self, message: str) -> NoReturn: ...

class IndexEntry(NamedTuple):
    name: str
    url: str
    has_credentials: bool

_PIP_INDEX_URL_OPTIONS: Final[frozenset[str]]
_PIP_DROPPED_VALUE_OPTIONS: Final[frozenset[str]]
_PIP_DROPPED_FLAG_OPTIONS: Final[frozenset[str]]

class RequirementsTxtInfo(NamedTuple):
    dependencies: list[str]
    editable_dependencies: list[str]
    python_versions: list[str]
    indexes: list[IndexEntry]
    skipped_options: list[str]

def _split_pip_option_token(token: str) -> tuple[str, str | None]: ...
def _strip_index_url_credentials(url: str) -> tuple[str, bool]: ...
def _uv_index_env_token(name: str) -> str: ...
def _index_name_from_url(url: str, used_names: set[str]) -> str: ...
def _build_index_entries(raw_urls: list[str]) -> list[IndexEntry]: ...
def _consume_next_value(
    tokens: list[str], i: int, *, guard_non_option: bool
) -> tuple[str | None, int]: ...
def _apply_pip_option(
    name: str,
    inline: str | None,
    tokens: list[str],
    i: int,
    index_urls: list[str],
    skipped: list[str],
) -> int: ...
def _parse_requirement_line(line: str) -> tuple[str | None, list[str], list[str]]: ...

_PEP_508_NAME_RE: re.Pattern[str]

def _is_likely_valid_pep508_dep(dep: str) -> bool: ...
def convert_version_preference(versions: list[str]) -> tuple[str, list[str]]: ...
def version_satisfies_constraints(
    version: str, min_version: str, max_version: str | None = None
) -> bool: ...
def remove_path(path: Path) -> None: ...
def _validate_python_version(value: str) -> str: ...

class Pyproject:
    path: Path
    requirements_path: Path
    def __init__(self, base: Path) -> None: ...
    @cached_property
    def content(self) -> str: ...
    def migrate_from_requirements_txt(self) -> Pyproject: ...
    @property
    def requires_python(self) -> tuple[str | None, str | None]: ...
    @property
    def exists(self) -> bool: ...
    @cached_property
    def has_project_section(self) -> bool: ...
    @property
    def can_be_created_from_requirements_txt(self) -> bool: ...
    @cached_property
    def requirements_txt_info(self) -> RequirementsTxtInfo: ...
    def print_migration_info(self) -> None: ...
    def _parse_requirements_file(self) -> RequirementsTxtInfo: ...
    def _parse_python_preference(self) -> list[str]: ...
    def _generate_content_with_project(
        self,
        project_name: str,
        description: str,
        dependencies: list[str],
        requires_python: str,
        indexes: list[IndexEntry] | None = None,
    ) -> str: ...
    @staticmethod
    def _uv_index_section(indexes: list[IndexEntry]) -> str: ...
    def with_project_section(
        self,
        project_name: str,
        description: str,
        dependencies: list[str],
        requires_python: str = ...,
    ) -> Pyproject: ...

def create_pyproject(
    target: Path,
    project_name: str,
    description: str,
    dependencies: list[str],
    python_version: str,
) -> Pyproject: ...

class LockFile:
    path: Path
    def __init__(self, base: Path) -> None: ...
    @property
    def exists(self) -> bool: ...
    @cached_property
    def content(self) -> str: ...
    def diff(self, uv_bin: UvBin, base: Path, *, verbose: bool) -> str: ...
    def diff_summary(self, old_lines: set[str]) -> str: ...
    def read_lockfile_lines(self) -> set[str]: ...

@dataclass(order=True, frozen=True)
class UvVersion:
    major: int
    minor: int
    patch: int
    @property
    def valid(self) -> bool: ...
    @staticmethod
    def unknown() -> UvVersion: ...
    @staticmethod
    def minimum() -> UvVersion: ...
    @staticmethod
    def from_string(version_str: str) -> UvVersion: ...

class UvBin:
    appenv_dir: Path
    bin: Path
    uv_dir: Path
    managed_uv: Path
    def __init__(self, appenv_dir: Path) -> None: ...
    def cmd(
        self,
        args: list[str],
        *,
        verbose: bool = ...,
        merge_stderr: bool = ...,
        quiet: bool = ...,
        cwd: str | None = ...,
    ) -> str: ...
    @cached_property
    def version(self) -> UvVersion: ...
    @staticmethod
    def get_uv_version(uv_path: Path) -> UvVersion: ...
    def _get_uv_bin(self) -> Path: ...
    def _try_uv_from_path(self) -> Path | None: ...
    def _try_uv_from_appenv_dir(self) -> Path | None: ...
    def _try_uv_from_nix_channel(self) -> Path | None: ...
    def _try_uv_from_nix_flake(self) -> Path | None: ...
    def _try_uv_from_pip(self) -> Path | None: ...
    def _try_uv_from_installer(self) -> Path | None: ...
    @staticmethod
    def _uv_platform_triple() -> str | None: ...
    def _resolve_pip_command(self) -> list[str] | None: ...
    def _cleanup_appenv_uv(self) -> None: ...

class NoValidUvError(RuntimeError): ...

class CommandError(Exception):
    returncode: int
    def __init__(self, message: str, returncode: int) -> None: ...

@dataclass(frozen=True)
class AppEnvSettings:
    verbose: bool
    extras: list[str]
    basedir: Path

@dataclass(frozen=True)
class InitParams:
    command_name: str
    dependencies: list[str]
    project_name: str
    description: str
    python_version: str

class AppEnv:
    appenv_dir: Path
    appenv_script: Path
    base: Path
    log_dir: Path
    original_cwd: Path
    settings: AppEnvSettings
    venv_link: Path
    venv_python: Path
    venv_real: Path
    def __init__(self, original_cwd: Path, settings: AppEnvSettings) -> None: ...
    def _build_env(self, overlays: dict[str, str] | None = ...) -> dict[str, str]: ...
    def run(self, command: str, argv: list[str]) -> None: ...
    # appenv itself and its sub-commands
    def meta(
        self, remaining_args: list[str] | None = None, prog: str = "appenv"
    ) -> None: ...
    def prepare(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> Path: ...
    def init(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def _resolve_init_target(self, args: Namespace | None) -> Path: ...
    def _resolve_init_params_with_eof_guard(
        self, args: Namespace | None, pyproject: Pyproject, target: Path
    ) -> InitParams: ...
    def _atomic_write_and_lock(
        self, params: InitParams, pyproject: Pyproject
    ) -> None: ...
    def migrate(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def python(self, args: Namespace, remaining: list[str]) -> None: ...
    def run_script(self, args: Namespace, remaining: list[str]) -> None: ...
    def run_uv(self, args: Namespace, remaining: list[str]) -> None: ...
    def show_version(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def reset(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def update_lockfile(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def self_update(
        self, args: Namespace | None = None, remaining: list[str] | None = None
    ) -> None: ...
    def _self_update_via_uvx(self, args: Namespace | None = None) -> None: ...
    # Helpers
    def _check_existing_project(self, pyproject: Pyproject) -> None: ...
    def _validate_init_params(self, params: InitParams) -> InitParams: ...
    def _resolve_init_params_noninteractive(
        self, args: Namespace, target: Path
    ) -> InitParams: ...
    def _resolve_init_params_interactive_new(
        self, pyproject: Pyproject, target: Path
    ) -> InitParams: ...
    def _check_venv_health(self) -> None: ...
    def _ensure_venv_symlinks(self) -> None: ...
    def _ensure_appenv_script(self, *, update: bool = False) -> None: ...
    def _uv_lock(self, uv: UvBin, *, diff: bool) -> str: ...
    def _uv_sync(
        self, *, dev_mode: bool, uv: UvBin, env: dict[str, str] | None = None
    ) -> None: ...
    def _set_up_logdir(self) -> Path: ...
    def _prepare_venv(self, *, dev_mode: bool) -> Path: ...
    def _set_up_command_symlink(
        self,
        command_name: str,
        project_name: str,
    ) -> None: ...
    def _prepare_appenv_dir(self) -> None: ...
    def _chdir_to_project(self, target: Path) -> None: ...
    @staticmethod
    def _extract_version(script: Path) -> str | None: ...

def ensure_uv(appenv_dir: Path) -> UvBin: ...
def ensure_pyproject(base: Path) -> Pyproject: ...
def ensure_lock_file(base: Path) -> LockFile: ...

_GITIGNORE_ENTRIES: list[str]

def ensure_gitignore(base: Path, entries: list[str]) -> None: ...
def _build_env(overlays: dict[str, str] | None = ...) -> dict[str, str]: ...
def cmd(
    c: str | list[str],
    *,
    merge_stderr: bool = ...,
    quiet: bool = ...,
    cwd: str | None = ...,
    env: dict[str, str] | None = ...,
) -> bytes: ...
def ensure_best_python(base: Path) -> None: ...
def find_available_pythons() -> list[tuple[str, str]]: ...
def print_colored_diff(
    old_content: str, new_content: str, fromfile: str, tofile: str
) -> bool: ...
def appenv_settings_from_env() -> AppEnvSettings: ...
def _dedup_preserve_order(items: list[str]) -> list[str]: ...

_CONSOLE_HIDDEN_EVENTS: frozenset[str]

class _ConsoleDiagnosticFilter(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool: ...

class ColoredConsoleFormatter(logging.Formatter):
    dim: str
    reset: str
    arrow: str
    def format(self, record: logging.LogRecord) -> str: ...

def setup_logging(command_name: str, log_dir: Path, *, verbose: bool) -> None: ...
def main() -> None: ...
